services:
  - type: web
    name: grow-a-garden-stock-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: SCRAPE_URL
        value: https://www.vulcanvalues.com/grow-a-garden/stock
